Update status-page-ci.yml

diff --git a/.github/workflows/status-page-ci.yml b/.github/workflows/status-page-ci.yml
--- a/.github/workflows/status-page-ci.yml
+++ b/.github/workflows/status-page-ci.yml
@@ -46,9 +46,9 @@ jobs:
     - name: Get Terraform Outputs
       run: |
         cd ./terraform/statuspage_pr
-        RDS_ENDPOINT=$(terraform output -raw rds_endpoint | tr -d '\n' | tr -d '\r')
-        EFS_FILESYSTEM_ID=$(terraform output -raw efs_filesystem_id | tr -d '\n' | tr -d '\r')
-        BASTION_IP=$(terraform output -raw bastion_public_ip | tr -d '\r')
+        RDS_ENDPOINT=$(terraform output -raw rds_endpoint | tr -d '\n' | tr -d '\r') || { echo "Error: rds_endpoint output not found"; exit 1; }
+        EFS_FILESYSTEM_ID=$(terraform output -raw efs_filesystem_id | tr -d '\n' | tr -d '\r') || { echo "Error: efs_filesystem_id output not found"; exit 1; }
+        BASTION_IP=$(terraform output -raw bastion_public_ip | tr -d '\n' | tr -d '\r') || { echo "Error: bastion_public_ip output not found"; exit 1; }
     
         echo "RDS_ENDPOINT=$RDS_ENDPOINT" >> $GITHUB_ENV
         echo "EFS_FILESYSTEM_ID=$EFS_FILESYSTEM_ID" >> $GITHUB_ENV
